### PR TITLE
stavemodifier (v5)

### PR DESCRIPTION
**Pull request by rvilarl**
Now that the extracts have been merged there is only one file changed and no visual differences!

### CODE REVIEW

**Comment by rvilarl** [comment]
Minor changes on TimeSignatures, KeySignatures and Clefs (current first)

pptr-canvas_Accidental Automatic_Accidentals Bravura_current
pptr-canvas_Accidental Automatic_Accidentals Bravura_reference
pptr-canvas_Accidental Automatic_Accidentals___C_major_scale_in_Ab Bravura_current
pptr-canvas_Accidental Automatic_Accidentals___C_major_scale_in_Ab Bravura_reference
pptr-canvas_Accidental Automatic_Accidentals___Key_C___Single_Octave Bravura_current
pptr-canvas_Accidental Automatic_Accidentals___Key_C___Single_Octave Bravura_reference
pptr-canvas_Annotation Bottom_Annotation Bravura_current
pptr-canvas_Annotation Bottom_Annotation Bravura_reference

**Comment by rvilarl** [comment]
Major changes on MultiMeasureRests due to the different font (current first)

Bravura
pptr-MultiMeasureRest Simple_Test Bravura svg_current
pptr-MultiMeasureRest Simple_Test Bravura svg_reference
Gonville
pptr-MultiMeasureRest Simple_Test Gonville svg_current
pptr-MultiMeasureRest Simple_Test Gonville svg_reference
Leland
pptr-MultiMeasureRest Simple_Test Leland svg_current
pptr-MultiMeasureRest Simple_Test Leland svg_reference
Petaluma
pptr-MultiMeasureRest Simple_Test Petaluma svg_current
pptr-MultiMeasureRest Simple_Test Petaluma svg_reference

**Comment by ronyeh** [comment]
Is it possible to use the time signature number glyphs for multimeasure rests?

https://w3c.github.io/smufl/latest/tables/time-signatures.html

**Comment by rvilarl** [comment]
> Is it possible to use the time signature number glyphs for multimeasure rests?
> 
> https://w3c.github.io/smufl/latest/tables/time-signatures.html

done, looks better

pptr-MultiMeasureRest Simple_Test Bravura svg_current
pptr-MultiMeasureRest Simple_Test Gonville svg_current
pptr-MultiMeasureRest Simple_Test Leland svg_current
pptr-MultiMeasureRest Simple_Test Petaluma svg_current

**Comment by rvilarl** [comment]
@ronyeh do you find this one good now with timemeasures?

**Comment by rvilarl** [comment]
@ronyeh, ready to review and move onto notes!

**Pull request merged**
