### PR TITLE
VexFlow.* API

### PR DESCRIPTION
**Pull request by ronyeh**
Small improvements and fixes on top of the recently merged VexFlow.* API PR.

More demos.
Automatically fix errors with eslint when `grunt` is run.

### CODE REVIEW

**Comment by ronyeh** [comment]
I ran `eslint --fix`.

I added the `eslint` task to the default `grunt` build. It slows down the build a bit but it'll keep the repo cleaner.

**Comment by ronyeh** [comment]
OK, I think it's good to go.

Let me know if you run into any issues with the new VexFlow.* namespace! :-) It is a breaking change but mostly you just need to remove the dot between `Vex` and `Flow` 😊.

**Comment by ronyeh** [comment]
Wait nevermind... eslint autofixed the qunit.js, which I did not want. Still need to figure that out.

**Comment by ronyeh** [comment]
OK, I figured out the issue with eslint. I think this is ready to review/merge.

**Review by rvilarl — APPROVED** [review]

**Pull request merged**
