### PR TITLE
glyphnote & clefnote bounding box

### PR DESCRIPTION
**Pull request by rvilarl**
No visual differences. New tests added

image

image

### CODE REVIEW

**Comment by ronyeh** [comment]
Are the text 11 and 9 supposed to be outside of the bounding boxes?

**Comment by rvilarl** [comment]
> Are the text 11 and 9 supposed to be outside of the bounding boxes?

All the modifiers are in now like in StaveNote. Ar you getting the 11 and 9 out?

**Comment by rvilarl** [comment]
@ronyeh @AaronDavidNewman @mscuthbert @0xfe Happy New Year! Thanks for your help.

**Comment by mscuthbert** [comment]
Happy new year all!

**Comment by rvilarl** [comment]
> > Are the text 11 and 9 supposed to be outside of the bounding boxes?
> 
> All the modifiers are in now like in StaveNote. Ar you getting the 11 and 9 out?

@ronyeh we never resolved this question.

**Comment by mscuthbert** [comment]
I'm just seeing boxes here again.  :-(

**Comment by rvilarl** [comment]
@mscuthbert thanks, I should not upload SVGs on these discussions.

**Comment by rvilarl** [comment]
> I'm just seeing boxes here again. :-(

@mscuthbert thanks, I should not upload SVGs on these discussions. Do you see it now?

**Comment by mscuthbert** [comment]
> @mscuthbert thanks, I should not upload SVGs on these discussions. Do you see it now?

Looks great to me, and I'm seeing F7(#11b9) in the bounding box as well, which is correct in current logic, but not ideal for tie placement, etc.  But working on it...

**Pull request merged**
