### PR TITLE
Use string literal union for key signature type

### PR DESCRIPTION
**Pull request by judocode**
Key signatures are a known set of string literals, so this improves the typing on them

### CODE REVIEW

**Comment by rvilarl** [comment]
@judocode Thanks! I like the PR and the approach. There are missing changes if we go this way: CancelKey should also be KeySpec and there are a number of functions in Tables that would no longer be needed. Before making the change, let us ask.
@ronyeh @AaronDavidNewman @mscuthbert @jaredjj3 what do you think?

**Comment by judocode** [comment]
Thanks @rvilarl ! I updated to add KeySpec to cancelKey. Should I do the same for alterKey?

**Comment by rvilarl** [comment]
No this is an array of accidentals.

**Comment by mscuthbert** [comment]
My feeling is that it's generally best to add the union string type at least to keep things compatible.  It can be annoying for a developer to have had code that works something like this:

```
const tonic: KeySpec = thisPitch.name;  // C, C#, etc.
if (mode == 'major') {
     return new KeySignature(tonic)
} else {
     return new KeySignature(tonic + 'm')
}
```

and then suddenly long existing code won't compile because `tonic + 'm'` is not a KeySpec.  I only find string literal types to be helpful when there are very few (like 2 or 3) and they're not things likely to be constructed from other strings.  Things like this, I think are better considered Runtime Errors than needing typing.

**Comment by mscuthbert** [comment]
@judocode -- I really appreciate your contribution I should have added. This project needs new contributors with the energy and thought you brought to this PR. Even though I had some disagreements with it as a particular, I hope to keep seeing your contributions going forward. :-)

**Pull request closed without merging**
