### PR TITLE
adjust big time signatures

### PR DESCRIPTION
**Pull request by rvilarl**
looking at the single number topic I saw that some fonts were not presenting the digits correctly. I also saw that the petaluma numbers were more separated than the others. I have adjusted the threshold and also have shifted half a line rather than a line.

### CODE REVIEW

**Comment by rvilarl** [comment]
current
TimeSignature Additive_Signature_Test MuseJazz svg_current
reference
TimeSignature Additive_Signature_Test MuseJazz svg_reference
current
TimeSignature Additive_Signature_Test Petaluma svg_current
reference
TimeSignature Additive_Signature_Test Petaluma svg_reference
current
TimeSignature Aggregate_Signature_Test MuseJazz svg_current
reference
TimeSignature Aggregate_Signature_Test MuseJazz svg_reference
current
TimeSignature Aggregate_Signature_Test Petaluma svg_current
reference
TimeSignature Aggregate_Signature_Test Petaluma svg_reference
current
TimeSignature Alternating_Signature_Test Petaluma svg_current
reference
TimeSignature Alternating_Signature_Test Petaluma svg_reference
current
TimeSignature Basic_Time_Signatures MuseJazz svg_current
reference
TimeSignature Basic_Time_Signatures MuseJazz svg_reference
current
TimeSignature Basic_Time_Signatures Petaluma svg_current
reference
TimeSignature Basic_Time_Signatures Petaluma svg_reference
current
TimeSignature Big_Signature_Test Finale_Broadway svg_current
reference
TimeSignature Big_Signature_Test Finale_Broadway svg_reference
current
TimeSignature Big_Signature_Test MuseJazz svg_current
reference
TimeSignature Big_Signature_Test MuseJazz svg_reference
current
TimeSignature Big_Signature_Test Petaluma svg_current
reference
TimeSignature Big_Signature_Test Petaluma svg_reference
current
TimeSignature Complex_Signature_Test Finale_Ash svg_current
reference
TimeSignature Complex_Signature_Test Finale_Ash svg_reference
current
TimeSignature Complex_Signature_Test MuseJazz svg_current
reference
TimeSignature Complex_Signature_Test MuseJazz svg_reference
current
TimeSignature Complex_Signature_Test Petaluma svg_current
reference
TimeSignature Complex_Signature_Test Petaluma svg_reference
current
TimeSignature Interchangeable_Signature_Test MuseJazz svg_current
reference
TimeSignature Interchangeable_Signature_Test MuseJazz svg_reference
current
TimeSignature Interchangeable_Signature_Test Petaluma svg_current
reference
TimeSignature Interchangeable_Signature_Test Petaluma svg_reference
current
TimeSignature Time_Signature_Change_Test Petaluma svg_current
reference
TimeSignature Time_Signature_Change_Test Petaluma svg_reference
current
TimeSignature Time_Signature_multiple_staves_alignment_test Petaluma svg_current
reference
TimeSignature Time_Signature_multiple_staves_alignment_test Petaluma svg_reference

**Comment by rvilarl** [comment]
@mscuthbert @AaronDavidNewman what do you think?

**Comment by mscuthbert** [comment]
To me current without the space looks better than reference. But I don't use big time signatures with a jazz font so I don't know if they add more space for legibility. But I would assume not.

**Comment by sschmidTU** [comment]
> current
> TimeSignature Additive_Signature_Test MuseJazz svg_current
> reference
> TimeSignature Additive_Signature_Test MuseJazz svg_reference

The numbers are often overlapping quite a bit now, so I'd probably prefer just a tiny bit more margin between them.
It's still readable though, so not a huge issue.

**Pull request merged**
